name: Android CI

#on:
#  push:
#    branches: [ "feature/*" ]
#  pull_request:
#    branches: [ "develop" ]
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: set up JDK 17
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create secure.properties
        run: echo "${{ secrets.SECURE_PROPERTIES }}" | base64 --decode > secure.properties

      - name: Create keystore properties
        run: echo "${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}" | base64 --decode > keystore.properties

      - name: Decode And Save Keystore Base64 # app.keystoer.jks 키 값을 디코드 해서 app/dev_ksystore.jks로 저장한다. (생략 가능)
        run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > app/beer.keystore

      - name: Create google-services.json # 환경변수(GOOGLE_SERVICES_JSON) 값의 내용을 기반으로 `app/google-services.json`를 만든다.
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      # apk
      - name: Build with Gradle
        run: ./gradlew clean assemblePlayStoreRelease

      - name: Upload Release Build to APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-beer-itda.apk
          path: app/build/outputs/apk/playStore/release
          if-no-files-found: error

      # aab
      - name: Build with Gradle
        run: ./gradlew clean bundlePlayStoreRelease

      - name: Upload Release Build to AAB Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-beer-itda.aab
          path: app/build/outputs/bundle/playStoreRelease
          if-no-files-found: error

#      - name: Print directory list
#        run: ls -R app/build/outputs
#        if: always()

#      - name: Create Github Release
#        uses: softprops/action-gh-release@v1
#        with:
#          generate_release_notes: true
#          files: |
#            android/app/build/outputs/apk/release/app-release.apk

#      - name: Upload artifact to Firebase App Distribution for apk
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.FIREBASE_APP_ID}}
#          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CLI_KEY }}
#          groups: tester
#          file: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload artifact to Firebase App Distribution for AAB
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          groups: tester
          file: app/build/outputs/bundle/playStoreRelease/app-playStore-release.aab

      - name: Create Release Branch
        run: |
          version_part=$(echo "${{inputs.release_version}}" | cut -d'-' -f1)
          suffix_part=$(echo "${{inputs.release_version}}" | cut -d'-' -f2)
          
          git checkout -b release/${{inputs.version_part}}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Update VERSION_NAME in Versions.kt
          sed -ie 's/const val VERSION_NAME = ".*"/const val VERSION_NAME = "${{inputs.release_version}}"/' buildSrc/src/main/kotlin/AndroidConfig.kt
          
          git commit -m "Automated commit by GitHub Actions to update version name" -a
          git push --set-upstream origin release/${{inputs.version_part}}
      

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # Pick up events even if the job fails or is canceled.
