name: Android CI

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create secure.properties
      run: echo "${{ secrets.SECURE_PROPERTIES }}" | base64 --decode > secure.properties
      
    - name: Decode And Save Keystore Base64 # app.keystoer.jks 키 값을 디코드 해서 app/dev_ksystore.jks로 저장한다. (생략 가능)
      run: echo "${{ secrets.DEV_KEYSTORE }}" | base64 --decode > ddd_beer_dev.keystore
          
    - name: Create google-services.json # 환경변수(GOOGLE_SERVICES_JSON) 값의 내용을 기반으로 `app/google-services.json`를 만든다.
      run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
        
    - name: Build with Gradle
      run: ./gradlew clean build

   # - name: Build debug # APK를 빌드한다. (디버그용)
   #   run: ./gradlew assembleDebug
