name: Android CI

on:
  push:
    branches: [ "release/test" ]
#  pull_request:
#    branches: [ "develop" ]
#on:
#  workflow_dispatch:
#    inputs:
#      release_env:
#        description: 'env'
#        type: choice
#        options:
#          - dev
#          - qa
#          - prod
#        required: true
#      release_version:
#        description: 'env'
#        type: choice
#        options:
#          - dev
#          - qa
#          - prod
#        required: true

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
        name: set up JDK 17
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: git log
        run: git log -G "VERSION_NAME = \"([0-9]+)\.([0-9]+)\.([0-9]+)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?\"" -- buildSrc/src/main/kotlin/AndroidConfig.kt | grep '^commit' | head -n 1 | awk '{print $2}'