name: deploy

on:
  workflow_dispatch:
    inputs:
      region:
        required: true
        type: choice
      env:
        required: true
        type: choice
        options:
          - GooglePlay
          - AppTester
          - Both

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo variables
