name: 안드로이드 배포

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: 환경
        options:
          - Dev
          - Firebase
          - PlayStore

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo variables
        run: |
          echo "env: ${{ github.event.inputs.env }}"