name: 안드로이드 배포

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: 환경
        options:
          - Dev
          - Firebase
          - PlayStore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: set up JDK 17
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Echo variables
        run: |
          echo "env: ${{ github.event.inputs.env }}"
          echo "sender : ${{ github.event.sender.login }}"